#!/bin/sh

#################################################
# in the LXC container config file set:        ##
# lxc.network.type = veth                      ##
# lxc.network.veth.pair = veth.container-name  ##
# lxc.network.flags = up                       ##
# lxc.network.script.up = /etc/lxc/ovsup       ##
# lxc.network.script.down = /etc/lxc/ovsdown   ##
#### do NOT set lxc.network.link = vmnet ########

BRIDGE=vmnet
NET_CONFIG=/etc/network/interfaces
# ovs-vsctl functionality built into lxc now: https://github.com/lxc/lxc/issues/590
#ovs-vsctl --may-exist add-br $BRIDGE
#ovs-vsctl --may-exist add-port $BRIDGE $5
if ! grep "allow-$BRIDGE $5" $NET_CONFIG; then
cat <<__EOF__>> $NET_CONFIG

allow-$BRIDGE $5
auto $5
iface $5 inet manual
        ovs_bridge $BRIDGE
        ovs_type OVSPort
__EOF__
fi

